### ISSUE TITLE
Rita import not working

### ISSUE THREAD

**Issue by smissu** [Ucnt/bro-json-to-tsv#2]
I think your script is leaving out the timestamp column for the conn logs. I get nothing for beacons when I import the logs into rita and output an html report. Also, when I look at the conn logs that are generated by the script I don't have data in the ts column.

I commented out your code in the json_to_tsv file where you are parsing the ts field and it works now. I can convert the data from JSON to TSV and import the data info rita.

code in question:
 #if field == "ts":
                 #   d = datetime.datetime.strptime(line_json[field], '%Y-%m-%dT%H:%M:%S.%fZ')
                 #   fields.append("%s.%s" % (d.strftime("%s"), d.microsecond))
                #else:

**Comment by Ucnt** [comment]
Just made a change, can you try a git pull and try again?

To note, the code you noted is as intended.  All fields can be added as is but, the timestamp has to be converted into epoch, from datetime.

Please try on the test files first, i.e.

- go into the bro-json-to-tsv folder
- run:
rm -rf tsv/*    # removes old tsv files
python3 run_parser.py -i json/ -o /tsv    # run the test files

I am getting all the appropriate fields, e.g. below for the conn

#fields	ts	uid	id.orig_h	id.orig_p	id.resp_h	id.resp_p	proto	service	duration	orig_bytes	resp_bytes	conn_state	local_orig	local_resp	missed_bytes	history	orig_pkts	orig_ip_bytes	resp_pkts	resp_ip_bytes	tunnel_parents	orig_cc	resp_cc	sensorname

1549263594.396462	CD2Vlj96bkGXWmpz8	192.168.1.1	32343	4.5.6.7	443	tcp	ssl	0.022095	547	3728	SF	True	False	0	ShADadFf	18	2046	14	8200	-	-	-	test-sensor

If that works on the test files but not on your files, can you send me an example of what your ts field has?  It should be in this format:  '%Y-%m-%dT%H:%M:%S.%fZ'

**Comment by Ucnt** [comment]
Wanted to check back in and see if it was working now.

**Comment by ltdan86** [comment]
Not sure if this happened pre or post the troubleshooting on this issue (just downloaded and tried out your script today - nice work!).  I'm getting "Error parsing <conn.log> - 'str' object is not callable".  It still creates the conn.log file, but with very little data compared to the original json.

**Comment by Ucnt** [comment]
Sorry...saw the issue. I had a print statement without the %. Should be
fixed.

**Comment by Ucnt** [comment]
Still seeing issues?

**Comment by ltdan86** [comment]
Fixing the print statement fixed my issue.  Works great!

**Comment by Ucnt** [comment]
@smissu, I'll close in a few days if nothing heard

**Comment by smissu** [comment]
Sorry about the late reply. I am out of the office until Monday. Feel free
to close the ticket. I will try it again when I get back to the office.

**Comment by Ucnt** [comment]
FYI, RITA now support JSON natively.
