### ISSUE TITLE
json to tsv fails

### ISSUE THREAD

**Issue by gigawatts** [Ucnt/bro-json-to-tsv#3]
I placed "http.log" in the json/ dir, then ran:
`python3 run_parser.py -i json/ -o tsv/`

The result is just the original http.log file being echo'ed to standard out, followed by the following error:
```
 - Error: 'list' object has no attribute 'keys'
Can't identify file type of json/http.log
100%|██████████████████████████████████████████████████████████████| 1/1 [00:44<00:00, 44.95s/it]
```

It creates an empty output tsv/http.log

If you would like to try yourself, here is the source http.log file I'm attempting to convert (part of the SANS Holiday Hack Challenge 2019)  https://downloads.elfu.org/http.log.gz

**Comment by Ucnt** [comment]
So, that's an array of http logs not just an http log.

**Comment by Ucnt** [comment]
@gigawatts, fixed my end of the issue (adding origin to the http field list)

Steps to make it work

1) Git pull the latest.  You'll see that type_mapper.py was updated.
2) Convert that http.log file from an array of json to one json item per line  (I don't want to give more details given Holiday Hack Challenge being the use case.  Hit me up if you get stuck)
3) Add that file and run it as normal.

Notes:
- RITA does not use the origin field so it will not show up in the TSV nor RITA results.   See here for their code where it's missing - https://github.com/activecm/rita/blob/master/parser/parsetypes/http.go 
- I haven't looked at the http logs but orgin can be a useful field.  Don't overlook it just because it's not in RITA.

**Comment by Ucnt** [comment]
Closing pending any further issues seen

**Comment by gigawatts** [comment]
When you say "one json item per line", do you mean "one log event per file" ?

Update:
I tried splitting the source json into one {"ts":"123,"uid":"BLAH",...} object per line (still all in the same file), and while it successfully ran through your script, spitting out what appears to be a TSV file, rita just says "No compatible log files found" when I try to import the tsv log into a new db.

**Comment by Ucnt** [comment]
Correct, like this with the first two lines.

{"ts":"2019-10-05T06:50:42-0800","uid":"ClRV8h1vYKWXN1G5ke","id.orig_h":"238.27.231.56","id.orig_p":60677,"id.resp_h":"10.20.3.80","id.resp_p":80,"trans_depth":1,"method":"GET","host":"srf.elfu.org","uri":"/14.10/Google/","referrer":"-","version":"1.0","user_agent":"Mozilla/5.0 (Windows; U; Windows NT 5.1; fr; rv:1.9.2b4) Gecko/20091124 Firefox/3.6b4 (.NET CLR 3.5.30729)","origin":"-","request_body_len":0,"response_body_len":232,"status_code":404,"status_msg":"Not Found","info_code":"-","info_msg":"-","tags":"(empty)","username":"-","password":"-","proxied":"-","orig_fuids":"-","orig_filenames":"-","orig_mime_types":"-","resp_fuids":"FUPWLQXTNsTNvf33","resp_filenames":"-","resp_mime_types":"text/html"}
{"ts":"2019-10-05T06:50:42-0800","uid":"ClRV8h1vYKWXN1G5ke","id.orig_h":"54.242.225.110","id.orig_p":60677,"id.resp_h":"10.20.3.80","id.resp_p":80,"trans_depth":2,"method":"GET","host":"srf.elfu.org","uri":"/api/weather?station_id=2992224,6052153,711134,3464708,4626739,99060,4381866,7850358","referrer":"-","version":"1.0","user_agent":"Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_1; en-US) AppleWebKit/533.4 (KHTML, like Gecko) Chrome/5.0.375.86 Safari/533.4","origin":"-","request_body_len":0,"response_body_len":3880,"status_code":200,"status_msg":"OK","info_code":"-","info_msg":"-","tags":"(empty)","username":"-","password":"-","proxied":"-","orig_fuids":"-","orig_filenames":"-","orig_mime_types":"-","resp_fuids":"FGDCoD4QXeSiJbb0Nk","resp_filenames":"-","resp_mime_types":"application/json"}

Just to cut to the chase you can do it with this:  jq -c .[] http.log > http.log.new

**Comment by gigawatts** [comment]
That is what I was just attempting (used the exact same jq command), but rita is not accepting the log.

rita just says "No compatible log files found" when I try to import the tsv log into a new db.

Is that because of the warning you mentioned related to origin ?

**Comment by Ucnt** [comment]
Shouldn't be. That field never makes it into the TSV

**Comment by gigawatts** [comment]
Here is my resulting TSV:

```
$ head -n10 logs/http-obj-per-line.log 
#separator \x09
#set_separator  ,
#empty_field    (empty)
#unset_field    -
#path   http
#open   0000-00-00-00-00-00
#fields ts      uid     id.orig_h       id.orig_p       id.resp_h       id.resp_p       trans_depth     method    host    uri     referrer        version user_agent      origin  request_body_len        response_body_len status_code     status_msg      info_code       info_msg        tags    username        password proxied  orig_fuids      orig_filenames  orig_mime_types resp_fuids      resp_filenames  resp_mime_types
#types  time    string  addr    port    addr    port    count   string  string  string  string  string  string    count   count   count   string  count   string  set[enum]       string  string  set[string]     vector[string]    vector[string]  vector[string]  vector[string]  vector[string]  vector[string]
-       ClRV8h1vYKWXN1G5ke      238.27.231.56   60677   10.20.3.80      80      1       GET     srf.elfu.org      /14.10/Google/  -       1.0     Mozilla/5.0 (Windows; U; Windows NT 5.1; fr; rv:1.9.2b4) Gecko/20091124 Firefox/3.6b4 (.NET CLR 3.5.30729)        -       0       232     404     Not Found       -       -(empty)  -       -       -       -       -       -       FUPWLQXTNsTNvf33        -       text/html
-       ClRV8h1vYKWXN1G5ke      54.242.225.110  60677   10.20.3.80      80      2       GET     srf.elfu.org      /api/weather?station_id=2992224,6052153,711134,3464708,4626739,99060,4381866,7850358    -       1.0       Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_1; en-US) AppleWebKit/533.4 (KHTML, like Gecko) Chrome/5.0.375.86 Safari/533.4     -       0       3880    200     OK      -       -       (empty) -       --
        -       -       -       FGDCoD4QXeSiJbb0Nk      -       application/json

```

**Comment by gigawatts** [comment]
It seems to be jumbling some of the fields around?

**Comment by Ucnt** [comment]
I see what you're saying.  Fixing now.

**Comment by Ucnt** [comment]
Ok that should do it.  Removed origin from the header and skip it when adding new lines.

**Comment by gigawatts** [comment]
it also seems to be dropping the ts field all together, replacing it with a "-"

**Comment by Ucnt** [comment]
Ah...weirder format than normal bro logs.  Fixing now too.

**Comment by gigawatts** [comment]
After that last commit, rita did find valid logs, so heading in the right direction :smile:

**Comment by Ucnt** [comment]
lol.  Updated datetime parsing.  Maybe they're using an older version of bro?...odd...either way, time is working now.

#fields	ts	uid	id.orig_h	id.orig_p	id.resp_h	id.resp_p	trans_depth	method	host	uri	referrer	version	user_agent	request_body_len	response_body_len	status_code	status_msg	info_code	info_msg	tags	username	password	proxied	orig_fuids	orig_filenames	orig_mime_types	resp_fuids	resp_filenames	resp_mime_types
#types	time	string	addr	port	addr	port	count	string	string	string	string	string	string	count	count	count	string	count	string	set[enum]	string	string	set[string]	vector[string]	vector[string]	vector[string]	vector[string]	vector[string]	vector[string]
1570272642.0	ClRV8h1vYKWXN1G5ke	238.27.231.56	60677	10.20.3.80	80	1	GET	srf.elfu.org	/14.10/Google/	-	1.0	Mozilla/5.0 (Windows; U; Windows NT 5.1; fr; rv:1.9.2b4) Gecko/20091124 Firefox/3.6b4 (.NET CLR 3.5.30729)	0	232	404	Not Found	-	-	(empty)	-	-	-	-	-	-	FUPWLQXTNsTNvf33	-	text/html
1570272642.0	ClRV8h1vYKWXN1G5ke	54.242.225.110	60677	10.20.3.80	80	2	GET	srf.elfu.org	/api/weather?station_id=2992224,6052153,711134,3464708,4626739,99060,4381866,7850358	-	1.0	Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_1; en-US) AppleWebKit/533.4 (KHTML, like Gecko) Chrome/5.0.375.86 Safari/533.4	0	3880	200	OK	-	-	(empty)	-	-	-	--	-	FGDCoD4QXeSiJbb0Nk	-	application/json

**Comment by Ucnt** [comment]
Any "-" now should just be where the JSON object doesn't have they key for the field that the TSV is looking for.

**Comment by gigawatts** [comment]
ok, thanks for the quick fixes! 

I'm not sure if there are still some messed up fields or if my RITA config is messed up, as this is what I'm getting back from rita import:

```
[+] Importing [/logs]:
[-] Verifying log files have not been previously parsed into the target dataset ...
[-] Parsing logs to: obj12-dataset ...
[-] Parsing /logs/http-obj-per-line.log -> obj12-dataset
[!] No Host data to analyze
	[!!] No local network traffic found, please check InternalSubnets in your RTIA config (/etc/rita/config.yaml)
[!] No Uconn data to analyze
	[!!] No local network traffic found, please check InternalSubnets in your RTIA config (/etc/rita/config.yaml)
[!] No DNS data to analyze
[!] No Hostname data to analyze
[!] No Beacon data to analyze
[-] UserAgent Analysis:       4949 / 4949  [==================] 100 %
[!] No certificate data to analyze
[-] Indexing log entries ...
[-] Updating metadatabase ...
[-] Done!

```

**Comment by Ucnt** [comment]
Looks right.  What doesn't look correct to you?  It's just HTTP logs so (I think?) all RITA will analyze is user agents.

**Comment by gigawatts** [comment]
Hmm, ok, I am brand new to RITA and bro/zeek logs, so all I have to compare it with is the another RITA challenge in this year's HHC that showed several more things for an http.log (long connections, BL Dest IPs, beacons, etc). 

I was hoping to gather some similar information from this http.log as well, but perhaps I am instead just digging a really deep rabbit hole for myself :rofl: and should move on to a different analysis approach.

Thank you again for your rapid replies!

**Comment by Ucnt** [comment]
I'll double check.  I thought http logs didn't do those other items.

**Comment by Ucnt** [comment]
Maybe some has to do with that the origin IPs are all public IPs?

i.e. This is the elfu.org http logs.  RITA is (pretty sure) looking for the source IP to be an internal IP.

Either way, not seeing where http logs would do long connections, BL, or beacons.

**Comment by gigawatts** [comment]
Ah, that makes sense (expecting internal source).

**Comment by Ucnt** [comment]
FYI, RITA now support JSON natively.
